name: Docker Image CI

on:
  push:
    branches: ["release", "release_test"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build using docker compose
        shell: bash
        run: |
          docker compose build

      - name: Push images
        shell: bash
        run: |
          docker tag obico-server-ml_api:latest ${{ env.REGISTRY }}/obico-server-ml_api:${{ $GITHUB_BASE_REF }}
          docker tag obico-server-ml_api:latest ${{ env.REGISTRY }}/obico-server-ml_api:${{ $GITHUB_SHA }}
          docker push ${{ env.REGISTRY }}/obico-server-ml_api:${{ $GITHUB_BASE_REF }}
